[package]
name = "rusberry-pi"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = "0.92"
actix-web = "4"
async-stream = "0.3"
onnxruntime = { version = "0.0.14", features = ["ndarray"] }
ndarray = "0.15"
