[package]
name = "rusberry-pi"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = "0.92"
actix-web = "4"
async-stream = "0.3"
ort = { version = "2.0.0-rc.10", features = ["ndarray"] }
ndarray = "0.15"
tokio="1.47.1"
